In [156]:
import pandas as pd

In [157]:
# import plotly
# plotly.tools.set_credentials_file(username='ashhadulislamplotly', api_key='fUP5hJXrd5y7PUDw5yBF')
from plotly.offline import plot,iplot
from plotly.graph_objs import Scatter
import plotly.plotly as py
import plotly.graph_objs as go

In [158]:
muslim_pop_df=pd.read_excel("District_muslim_Population-2001.xls")

In [159]:
#strip spaces from columns
muslim_pop_df= muslim_pop_df.rename(columns=lambda x: x.strip())

In [160]:
muslim_pop_df.head()

,S No,State,Districts,District Total Population,District Total Muslim Population,% of Total Indian Muslims,Total Urban Muslims,Total Rural Muslims,% of Total District Pop.
0,1.0,Andhra Pradesh,Hyderabad,3829753.0,1576583.0,1.140895,1576583.0,0.0,41.166702
1,2.0,Andhra Pradesh,Kurnool,3529494.0,572404.0,0.414220,231343.0,341061.0,16.217735
2,3.0,Andhra Pradesh,Guntur,4465144.0,487839.0,0.353025,223814.0,264025.0,10.925493
3,4.0,Andhra Pradesh,Rangareddi,3575064.0,408281.0,0.295453,273996.0,134285.0,11.420243
4,5.0,Andhra Pradesh,Anantapur,3640478.0,389201.0,0.281646,231408.0,157793.0,10.690931

In [161]:
#now filter by % of population >25
muslim_pop_df=muslim_pop_df[muslim_pop_df["% of Total District Pop."]>25]

In [162]:
muslim_pop_df.head()

,S No,State,Districts,District Total Population,District Total Muslim Population,% of Total Indian Muslims,Total Urban Muslims,Total Rural Muslims,% of Total District Pop.
0,1.0,Andhra Pradesh,Hyderabad,3829753.0,1576583.0,1.140895,1576583.0,0.0,41.166702
38,39.0,Assam,Dhubri,1637344.0,1216455.0,0.880288,71660.0,1144795.0,74.294406
39,40.0,Assam,Nowgong,2314629.0,1180267.0,0.854101,61069.0,1119198.0,50.991628
40,41.0,Assam,Barpeta,1647201.0,977943.0,0.707689,16522.0,961421.0,59.369986
42,43.0,Assam,Darrang,1504320.0,534658.0,0.386906,9657.0,525001.0,35.541507

In [163]:
muslim_pop_df=muslim_pop_df.sort_values(by=['% of Total District Pop.'],ascending=False)

In [164]:
muslim_pop_df.head()

,S No,State,Districts,District Total Population,District Total Muslim Population,% of Total Indian Muslims,Total Urban Muslims,Total Rural Muslims,% of Total District Pop.
185,186.0,J & Kashmir,Anantnag,1172434.0,1154780.0,0.835657,160470.0,994310.0,98.494244
190,191.0,J & Kashmir,Badgam,629309.0,617212.0,0.446646,67375.0,549837.0,98.077733
188,189.0,J & Kashmir,Pulwama,652607.0,637008.0,0.460971,65193.0,571815.0,97.609741
186,187.0,J & Kashmir,Baramula,1169780.0,1141162.0,0.825803,183733.0,957429.0,97.553557
189,190.0,J & Kashmir,Kupwara,650393.0,633263.0,0.458261,23678.0,609585.0,97.366208

In [165]:
muslim_pop_df.columns

Index(['S No', 'State', 'Districts', 'District Total Population',
       'District Total Muslim Population', '% of Total Indian Muslims',
       'Total Urban Muslims', 'Total Rural Muslims',
       '% of Total District Pop.'],
      dtype='object')

In [166]:
#ignore Kashmir as we are not analyzing it
# muslim_pop_df = muslim_pop_df.drop(muslim_pop_df["State"]=="J & Kashmir").index
muslim_pop_df = muslim_pop_df.drop(muslim_pop_df[muslim_pop_df.State =="J & Kashmir"].index)

In [206]:
muslim_pop_df

,S No,State,Districts,District Total Population,District Total Muslim Population,% of Total Indian Muslims,Total Urban Muslims,Total Rural Muslims,% of Total District Pop.
258,259.0,Lakshadweep,Lakshadweep,60650.0,57903.0,0.041902,25229.0,32674.0,95.470734
38,39.0,Assam,Dhubri,1637344.0,1216455.0,0.880288,71660.0,1144795.0,74.294406
244,245.0,Kerala,Malappuram,3625471.0,2484576.0,1.797965,241710.0,2242866.0,68.531123
64,65.0,Bihar,Kishanganj,1296348.0,876105.0,0.633994,57138.0,818967.0,67.582547
575,576.0,West Bengal,Murshidabad,5866569.0,3735380.0,2.703110,310721.0,3424659.0,63.672310
40,41.0,Assam,Barpeta,1647201.0,977943.0,0.707689,16522.0,961421.0,59.369986
48,49.0,Assam,Hailakandi,542872.0,312849.0,0.226393,8967.0,303882.0,57.628502
45,46.0,Assam,Goalpara,822035.0,441516.0,0.319503,33197.0,408319.0,53.710122
43,44.0,Assam,Karimganj,1007976.0,527214.0,0.381519,6603.0,520611.0,52.304222
39,40.0,Assam,Nowgong,2314629.0,1180267.0,0.854101,61069.0,1119198.0,50.991628
578,579.0,West Bengal,Maldah,3290468.0,1636171.0,1.184016,26575.0,1609596.0,49.724568
498,499.0,Uttar Pradesh,Rampur,1923739.0,945277.0,0.684050,326842.0,618435.0,49.137487
46,47.0,Assam,Marigaon,776256.0,369398.0,0.267315,6162.0,363236.0,47.587136
581,582.0,West Bengal,Uttar Dinajpur,2441794.0,1156503.0,0.836904,24478.0,1132025.0,47.362841
492,493.0,Uttar Pradesh,Moradabad,3810983.0,1735381.0,1.255809,633406.0,1101975.0,45.536309
61,62.0,Bihar,Katihar,2392638.0,1017495.0,0.736311,44208.0,973287.0,42.526074
494,495.0,Uttar Pradesh,Bijnor,3131619.0,1306329.0,0.945326,508746.0,797583.0,41.714174
0,1.0,Andhra Pradesh,Hyderabad,3829753.0,1576583.0,1.140895,1576583.0,0.0,41.166702
63,64.0,Bihar,Araria,2158608.0,887972.0,0.642581,48480.0,839492.0,41.136325
511,512.0,Uttar Pradesh,Jyotiba Phule Nagar *,1499068.0,590308.0,0.427177,239179.0,351129.0,39.378334
496,497.0,Uttar Pradesh,Saharanpur,2896863.0,1132919.0,0.819837,375099.0,757820.0,39.108477
47,48.0,Assam,Bongaigaon,904835.0,348573.0,0.252245,8861.0,339712.0,38.523377
493,494.0,Uttar Pradesh,Muzaffarnagar,3543362.0,1349629.0,0.976660,420393.0,929236.0,38.088939
245,246.0,Kerala,Kozhikode,2879131.0,1078750.0,0.780638,422485.0,656265.0,37.467903
154,155.0,Haryana,Gurgaon,1660289.0,617918.0,0.447157,25575.0,592343.0,37.217496
62,63.0,Bihar,Purnia,2543942.0,935239.0,0.676786,49680.0,885559.0,36.763377
506,507.0,Uttar Pradesh,Balrampur *,1682350.0,617675.0,0.446981,63709.0,553966.0,36.715012
44,45.0,Assam,Cachar,1444921.0,522051.0,0.377783,39366.0,482685.0,36.130072
42,43.0,Assam,Darrang,1504320.0,534658.0,0.386906,9657.0,525001.0,35.541507
583,584.0,West Bengal,Birbhum,3015422.0,1057861.0,0.765522,45393.0,1012468.0,35.081690
499,500.0,Uttar Pradesh,Bahraich,2381072.0,829361.0,0.600168,141445.0,687916.0,34.831412
252,253.0,Kerala,Kasaragod,1204078.0,413063.0,0.298913,86108.0,326955.0,34.305336
495,496.0,Uttar Pradesh,Bareilly,3618589.0,1226386.0,0.887475,556104.0,670282.0,33.891276
576,577.0,West Bengal,South 24 Parganas,6906689.0,2295967.0,1.661478,301989.0,1993978.0,33.242658
562,563.0,Uttranchal,Hardwar,1447187.0,478274.0,0.346103,111897.0,366377.0,33.048528
497,498.0,Uttar Pradesh,Meerut,2997361.0,975715.0,0.706077,540147.0,435568.0,32.552469
205,206.0,Jharkhand,Pakaur *,701664.0,227069.0,0.164319,9107.0,217962.0,32.361501
203,204.0,Jharkhand,Sahibganj,927770.0,290060.0,0.209902,21181.0,268879.0,31.264214
403,404.0,Pondichery,Mahe,36828.0,11411.0,0.008258,11411.0,0.0,30.984577
120,121.0,Delhi,Central *,646385.0,193137.0,0.139764,193137.0,0.0,29.879561
509,510.0,Uttar Pradesh,Siddharthnagar,2040085.0,600336.0,0.434433,26341.0,573995.0,29.427009
247,248.0,Kerala,Kannur,2408956.0,665648.0,0.481697,379913.0,285735.0,27.632219
118,119.0,Delhi,North East *,1768061.0,481607.0,0.348515,463946.0,17661.0,27.239275
246,247.0,Kerala,Palakkad,2617482.0,703596.0,0.509158,79824.0,623772.0,26.880643
253,254.0,Kerala,Wayanad,780619.0,209758.0,0.151791,10841.0,198917.0,26.870727
535,536.0,Uttar Pradesh,Shrawasti *,1176391.0,301117.0,0.217903,15480.0,285637.0,25.596677
580,581.0,West Bengal,Nadia,4604827.0,1170282.0,0.846875,45974.0,1124308.0,25.414245

In [209]:
# def analyze_district(state,district,year):
state="Uttar Pradesh"
district="Jyotiba Phule Nagar "
year="2014"
#open the corresponding state file for 2014
df_results = pd.read_excel(state+".xlsx",sheet_name=year)

In [210]:
df_results.head()

,Sl. No.,Election Status,Candidate Name,Constituency,Gender,Age,Party,Total Electors,Turn Out(%),Candidate Votes(%),Count Of Votes
0,1,Won,Dasrath Tirkey,Alipurduars,M,47,AITC,1464809,83.53,29.62,362416.0
1,2,Runner-Up,Manohar Tirkey,Alipurduars,M,61,RSP,1464809,83.53,27.87,341004.0
2,3,Lost,Birendra Bara (Oraon),Alipurduars,M,31,BJP,1464809,83.53,27.45,335865.0
3,4,Forfeited,Joseph Munda,Alipurduars,M,43,INC,1464809,83.53,9.54,116727.0
4,5,Forfeited,Eliash Narjinary,Alipurduars,M,62,BSP,1464809,83.53,0.90,11011.0

In [211]:
district_constituency_mapper={
    "Maldah":["Maldaha Uttar","Maldaha Dakshin"],
    "Jyotiba Phule Nagar":["Amroha"],
    "Cachar":["Silchar"],
    "Darrang":["Mangaldoi"],
    "South  24 Parganas":["Diamond Harbour"],
    "Nadia":["Krishnanagar","Ranaghat"]
    }

In [212]:
constituencies=[]
district=district.strip()
if district in district_constituency_mapper.keys():
    constituencies=district_constituency_mapper[district]
else:
    constituencies.append(district)

In [213]:
print(constituencies)

['Murshidabad']

In [215]:
#find the given district in that state
df_results_districtwise=df_results[df_results["Constituency"]==constituencies[0]]

In [216]:
df_results_districtwise.head()

,Sl. No.,Election Status,Candidate Name,Constituency,Gender,Age,Party,Total Electors,Turn Out(%),Candidate Votes(%),Count Of Votes
394,395,Won,Badaruddoza Khan,Murshidabad,M,59,CPI(M),1527720,84.29,33.15,NaN
395,396,Runner-Up,Abdul Mannan Hossain,Murshidabad,M,61,INC,1527720,84.29,31.72,NaN
396,397,Lost,Ali Mohammad,Murshidabad,M,50,AITC,1527720,84.29,22.44,NaN
397,398,Forfeited,Sujit Kumar Ghosh,Murshidabad,M,72,BJP,1527720,84.29,7.85,NaN
398,399,Forfeited,Md. Najmul Hoque,Murshidabad,M,38,AIUDF,1527720,84.29,0.88,NaN

In [200]:
df_results_districtwise_winner=df_results_districtwise[df_results_districtwise["Election Status"]=="Won"]

In [201]:
if df_results_districtwise_winner.iloc[0]["Party"] in "BJP":
    print("This is of interest")

In [174]:
#Now sort the district wise result by vote count
df_results_districtwise=df_results_districtwise.sort_values(by=['Count Of Votes'],ascending=False)

In [175]:
df_results_districtwise

,Sl. No.,Election Status,Candidate Name,Constituency,Gender,Age,Party,Total Electors,Turn Out(%),Candidate Votes(%),Count Of Votes
128,129,Won,Rajen Gohain,Nowgong,M,63,BJP,1518663,81.0,40.17,494138
129,130,Runner-Up,Jonjonali Baruah,Nowgong,M,55,INC,1518663,81.0,28.50,350583
130,131,Lost,Dr. Aditya Langthasa,Nowgong,M,48,AIUDF,1518663,81.0,25.53,314048
131,132,Forfeited,Mridula Barkakoty,Nowgong,M,53,AGP,1518663,81.0,2.86,35181
132,133,Forfeited,Md Faruk Hazarika,Nowgong,M,42,IND,1518663,81.0,0.92,11317
133,134,Forfeited,Dipak Kumar Borah,Nowgong,M,50,AITC,1518663,81.0,0.56,6888
134,135,Forfeited,Selima Sultana,Nowgong,M,28,IND,1518663,81.0,0.53,6519
135,136,Forfeited,Rafiqul Islam,Nowgong,M,26,AIFB,1518663,81.0,0.23,2829

In [176]:
num_of_candidates=df_results_districtwise.shape[0]

In [177]:
winner_votes=int(df_results_districtwise_winner.iloc[0]["Count Of Votes"])

In [178]:
num_votes=df_results_districtwise["Count Of Votes"].tolist()

In [179]:
num_votes

[494138, 350583, 314048, 35181, 11317, 6888, 6519, 2829]

In [180]:
parties=df_results_districtwise["Party"].tolist()

In [181]:
parties

['BJP', 'INC', 'AIUDF', 'AGP', 'IND', 'AITC', 'IND', 'AIFB']

In [182]:
colors=[]
colors = ['rgba(104,204,204,1)']*len(parties)
colors[0]='rgba(221,104,94,1)'
print(colors)
# color=['rgba(204,204,204,1)', 'rgba(222,45,38,0.8)',
#                'rgba(204,204,204,1)', 'rgba(204,204,204,1)',
#                'rgba(204,204,204,1)'

['rgba(221,104,94,1)', 'rgba(104,204,204,1)', 'rgba(104,204,204,1)', 'rgba(104,204,204,1)', 'rgba(104,204,204,1)', 'rgba(104,204,204,1)', 'rgba(104,204,204,1)', 'rgba(104,204,204,1)']

In [183]:
data = [go.Bar(
            x=parties,
            y=num_votes,
    marker=dict(
        color=colors),
    
    
    )]
layout = go.Layout(
    title=state+' '+district+' 2014',
)

fig = go.Figure(data=data, layout=layout)

#to create a div for the graph
graph_div=plot(fig,output_type='div')

#to plot here
py.iplot(fig, filename='basic-vote-var')




# py.iplot(data, filename='basic-bar')

In [184]:
margin=num_votes[0]-num_votes[1]
print("BJP won by ",margin," votes")

BJP won by  143555  votes

In [185]:
#pitting top two against winner
mod_parties=[]
mod_parties.append(parties[0])
mod_parties.append(parties[1]+" & "+parties[2])
mod_num_votes=[]
mod_num_votes.append(num_votes[0])
mod_num_votes.append(num_votes[1]+num_votes[2])
colors = ['rgba(104,204,204,1)']*len(mod_parties)
colors[0]='rgba(221,104,94,1)'

In [186]:
data = [go.Bar(
            x=mod_parties,
            y=mod_num_votes,
    marker=dict(
        color=colors),

    )]
layout = go.Layout(
    title=state+' '+district+' 2014',
)

fig = go.Figure(data=data, layout=layout)
#to create a div for the graph
graph_div=plot(fig,output_type='div')


py.iplot(fig, filename='basic-vote-var')

In [187]:
if mod_num_votes[0]>mod_num_votes[1]:
    print("BJP still wins by ",mod_num_votes[0]-mod_num_votes[1]," votes")
else:
    print("BJP loses by ",mod_num_votes[1]-mod_num_votes[0]," votes")

BJP loses by  170493  votes

In [188]:
#pitting top three against winner
mod_parties=[]
mod_parties.append(parties[0])
mod_parties.append(parties[1]+" & "+parties[2]+" & "+parties[3])
mod_num_votes=[]
mod_num_votes.append(num_votes[0])
mod_num_votes.append(num_votes[1]+num_votes[2]+num_votes[3])
colors = ['rgba(104,204,204,1)']*len(mod_parties)
colors[0]='rgba(221,104,94,1)'

In [189]:
data = [go.Bar(
            x=mod_parties,
            y=mod_num_votes,
    marker=dict(
        color=colors),

    )]
layout = go.Layout(
    title=state+' '+district+' 2014',
)

fig = go.Figure(data=data, layout=layout)
#to create a div for the graph
graph_div=plot(fig,output_type='div')


py.iplot(fig, filename='basic-vote-var')

In [190]:
if mod_num_votes[0]>mod_num_votes[1]:
    print("BJP still wins by ",mod_num_votes[0]-mod_num_votes[1]," votes")
else:
    print("BJP loses by ",mod_num_votes[1]-mod_num_votes[0]," votes")

BJP loses by  205674  votes